name: zammad
description: Zammad is a web based open source helpdesk/customer support system
homepage: https://zammad.org
notifications: false
targets:
  centos-7:
    dependencies:
      - curl
      - elasticsearch
      - nginx
      - postgresql-server
      - which
      - imlib2
    build_dependencies:
      - http://springdale.math.ias.edu/data/puias/7/x86_64/os/Addons/Packages/imlib2-devel-1.4.5-9.sdl7.x86_64.rpm
  debian-8:
    dependencies:
      - curl
      - elasticsearch
      - nginx|apache2
      - postgresql|mysql-server|mariadb-server|sqlite
      - libimlib2
    build_dependencies:
      - libimlib2-dev
  debian-9:
    dependencies:
      - curl
      - elasticsearch
      - nginx|apache2
      - postgresql|mariadb-server|sqlite
      - libimlib2
    build_dependencies:
      - libimlib2-dev
  ubuntu-16.04:
    dependencies:
      - curl
      - elasticsearch
      - nginx|apache2
      - postgresql|mysql-server|mariadb-server|sqlite
      - libimlib2
    build_dependencies:
      - libimlib2-dev
  ubuntu-18.04:
    dependencies:
      - curl
      - elasticsearch
      - nginx|apache2
      - postgresql|mysql-server|mariadb-server|sqlite
      - libimlib2
    build_dependencies:
      - libimlib2-dev
  sles-12:
    dependencies:
      - curl
      - elasticsearch
      - nginx
      - postgresql-server
      - imlib2
    build_dependencies:
      - imlib2-devel
before:
  - contrib/packager.io/before.sh
after:
  - contrib/packager.io/after.sh
env:
  - RAILS_ENV=production
  - ZAMMAD_BIND_IP=127.0.0.1
  - ZAMMAD_RAILS_PORT=3000
  - ZAMMAD_WEBSOCKET_PORT=6042
services:
  - postgres
after_install: contrib/packager.io/postinstall.sh
