name: zammad
description: Zammad is a web based open source helpdesk/customer support system
homepage: https://zammad.org
notifications: false
targets:
  debian-9:
    dependencies:
      - curl
      - elasticsearch
      - nginx|apache2
      - postgresql|mariadb-server|sqlite
      - libimlib2
    build_dependencies:
      - libimlib2-dev
  sles-12:
    dependencies:
      - curl
      - elasticsearch
      - nginx
      - postgresql-server
      - libImlib2-1
    build_dependencies:
      - https://ftp5.gwdg.de/pub/opensuse/discontinued/distribution/12.3/repo/oss/suse/x86_64/libImlib2-1-1.4.5-12.1.1.x86_64.rpm
before:
  - contrib/packager.io/before.sh
after:
  - contrib/packager.io/after.sh
env:
  - RAILS_ENV=production
  - ZAMMAD_BIND_IP=127.0.0.1
  - ZAMMAD_RAILS_PORT=3000
  - ZAMMAD_WEBSOCKET_PORT=6042
services:
  - postgres
after_install: contrib/packager.io/postinstall.sh
